export default class Command extends UiCommand {
    static help: string;
    static label: string;
    static example: string;
    /**
     * @param {Partial<Command>} input
     */
    constructor(input?: Partial<Command>);
    /** @type {string} */
    cwd: string;
    /** @type {FileSystem} */
    fs: FileSystem;
    /** @type {number} */
    timeout: number;
    /** @type {FileEntry} */
    file: FileEntry;
    /** @type {import("../../FileProtocol.js").ParsedFile} */
    parsed: import("../../FileProtocol.js").ParsedFile;
    /**
     * @returns {AsyncGenerator<boolean | string | UiOutput>}
     *
     *  - `boolean` - at the end to provide a result of the run
     *  - `string` - the content for the next chat message. `#### [Generated by LLiMo](llimo)`
     *  - `UiOutput` - show the result to user (output)
     */
    run(): AsyncGenerator<boolean | string | UiOutput>;
}
import { UiCommand } from "../../cli/Ui.js";
import { FileSystem } from "../../utils/FileSystem.js";
import { FileEntry } from "../../FileProtocol.js";
import { UiOutput } from "../../cli/UiOutput.js";
