packages:
  - apps/*
  # @nan0web packages
  - packages/auth-browser
  - packages/auth-core
  - packages/auth-db
  - packages/auth-node
  - packages/auth-ssr
  - packages/changelog
  - packages/co
  - packages/core
  - packages/db
  - packages/db-browser
  - packages/db-fs
  - packages/event
  - packages/html
  - packages/http
  - packages/http-node
  - packages/i18n
  - packages/interface
  - packages/llimo
  - packages/log
  - packages/mail
  - packages/markdown
  - packages/net
  - packages/protocol
  - packages/release
  - packages/story
  - packages/test
  - packages/transformer
  - packages/types
  - packages/xml
  - packages/ui
  - packages/ui-cli
  - packages/ui-core
  - packages/ui-react
  - packages/ui-react-bootstrap
  - packages/verse
