import { ModelAsApp, result, show, progress } from '@nan0web/ui'
import { ArchitectureAuditor } from '@nan0web/inspect'
import { Markdown } from '@nan0web/markdown'
import { createT } from '@nan0web/i18n'

/**
 * @typedef {Object} TaskSummary
 * @property {number} total
 * @property {number} completed
 */

/**
 * @typedef {Object} ModuleAuditResult
 * @property {string} name
 * @property {string} type
 * @property {string} path
 * @property {Record<string, TaskSummary>} files
 * @property {boolean} isCommercial
 * @property {string} license
 * @property {import('@nan0web/inspect').ArchitectureAuditor} [archScore]
 */

export default class AuditMonorepoApp extends ModelAsApp {
	static UI = {
		title: 'Ecosystem Audit 3.0',
		scanning: 'Analyzing {type}: {name}',
		completed: 'Audit completed. Found {count} active modules.',
		reportUpdated: 'Ecosystem report updated: STATUS.md',
		dbRequired: 'Database is required to run audit',
	}

	/**
	 * @returns {AsyncGenerator<import('@nan0web/ui').Intent, import('@nan0web/ui').ResultIntent, any>}
	 */
	async *run() {
		if (this.help) return yield* super.run()

		const { t, db } = this._

		if (!db) {
			yield show(t(AuditMonorepoApp.UI.dbRequired))
			return result({ ok: false })
		}

		/** @type {ModuleAuditResult[]} */
		const scanned = []
		const standardDocs = ['{lang}/README', '{lang}/project', 'README', 'project']

		for (const type of ['packages', 'apps']) {
			const entries = await db.listDir(`@app/${type}`)
			let i = 0

			for (const entry of entries) {
				if (!entry.isDirectory || entry.name.startsWith('.') || entry.name === 'node_modules')
					continue

				const name = entry.name
				const pkgPath = `${type}/${name}`

				yield progress(t(AuditMonorepoApp.UI.scanning, { type, name }), ++i)

				// 1. Detect Identity & Version
				const pkgJson = await db.loadDocument(`@app/${pkgPath}/package.json`)
				const version = pkgJson?.version ?? '0.0.0'

				// 2. Detect Locales via docs/index
				const docsIndex = await db.fetch(`@app/${pkgPath}/docs/index`)
				const langs = docsIndex?.langs ?? []

				const docs = new Set()
				for (const pattern of standardDocs) {
					docs.add(pattern)
					for (const lang of langs) {
						const p = createT({}, 'en')
						docs.add(p(pattern, { lang: lang.locale }))
					}
				}
				const pages = Array.from(docs).map(String).filter(l => !l.includes('{lang}'))
				// 3. Parse Tasks & Extract Goal
				/** @type {Record<string, TaskSummary>} */
				const files = {}
				let goal = null

				for (const target of pages) {
					const content = await db.loadDocument(`@app/${pkgPath}/${target}`)
					if (content) {
						files[target] = this.parseTasks(content)
					}
				}

				// 4. Run Architecture Audit via @nan0web/inspect
				const archScore = await this.runArchAudit(pkgPath)

				scanned.push({
					name,
					type,
					path: pkgPath,
					files,
					goal,
					langs,
					version,
					license: pkgJson?.license || 'ISC',
					isCommercial: type === 'apps' || pkgJson?.commercial,
					archScore,
				})
			}
		}

		yield show(t(AuditMonorepoApp.UI.completed, { count: scanned.length }), 'success')

		// 6. Generate Report
		const mdContent = this.generateReport(scanned)
		await db.saveDocument('@app/STATUS.md', mdContent)

		yield show(t(AuditMonorepoApp.UI.reportUpdated), 'success')
		return result({ scanned })
	}

	/**
	 * @param {string} content
	 * @returns {string|null}
	 */
	extractGoal(content) {
		if (!content) return null
		const text = typeof content === 'string' ? content : content.raw || content.content || ''
		if (!text) return null

		const lines = text
			.split('\n')
			.map((l) => l.trim())
			.filter(Boolean)
		// Skip title (# ...) and find first paragraph
		const goalLine = lines.find(
			(l) => !l.startsWith('#') && !l.startsWith('>') && !l.startsWith('-'),
		)
		return goalLine ? goalLine.split('.')[0] + '.' : null // First sentence
	}

	/**
	 * Extracts task statistics from markdown content.
	 * @param {string} content
	 * @returns {TaskSummary}
	 */
	generateReport(scanned) {
		const { t } = this._
		const doc = new Markdown()

		doc.write(t('🏗️ NanWeb Ecosystem Status'), 'h1')
		doc.write(
			t('Generated by AuditMonorepoApp 4.0 on {date}', { date: new Date().toISOString() }),
			'blockquote',
		)
		doc.write('')

		// 1. Group by Maturity
		const categories = {
			'🚀 CORE (v3.0+)': [],
			'🏗️ LAB (In Dev)': [],
			'🌱 SEEDS (Ideas)': [],
		}

		for (const item of scanned) {
			const version = item.version || '0.0.0'
			const hasProject = !!item.files['project.md']
			const hasTasks = item.files['next.md']?.total > 0 || item.files['project.md']?.total > 0

			if (version.startsWith('3.')) {
				categories['🚀 CORE (v3.0+)'].push(item)
			} else if (hasProject || hasTasks) {
				categories['🏗️ LAB (In Dev)'].push(item)
			} else {
				categories['🌱 SEEDS (Ideas)'].push(item)
			}
		}

		for (const [title, modules] of Object.entries(categories)) {
			if (modules.length === 0) continue

			doc.write(t(title), 'h2')
			const tableData = []

			for (const item of modules.sort((a, b) => a.name.localeCompare(b.name))) {
				const goal = item.goal || t('*Missing Purpose*')

				let total = 0,
					completed = 0
				for (const f in item.files) {
					total += item.files[f].total || 0
					completed += item.files[f].completed || 0
				}

				// Health Score
				let health = '-'
				if (item.archScore) {
					const score = Math.round(item.archScore.ratio * 100)
					health = isNaN(score)
						? '🛠️ ?%'
						: score >= 90
							? `💎 ${score}%`
							: score >= 60
								? `🛠️ ${score}%`
								: `⚠️ ${score}%`
				}

				const versionLabel = item.version ? `\`v${item.version}\`` : '-'
				const tasksLabel = total > 0 ? `${completed}/${total}` : '-'
				const typeLabel = item.type === 'apps' ? '📱' : '📦'
				const langsLabel =
					item.langs?.length > 0
						? item.langs.map((l) => (typeof l === 'string' ? l : l.locale).toUpperCase()).join(', ')
						: '-'

				tableData.push({
					[t('Module')]: `${typeLabel} **${item.name}**`,
					[t('Version')]: versionLabel,
					[t('Goal')]: goal,
					[t('Langs')]: langsLabel,
					[t('Tasks')]: tasksLabel,
					[t('Health')]: health,
					[t('License')]: item.license,
				})
			}

			doc.table(tableData)
			doc.write('')
		}

		return doc.toString()
	}

	/**
	 * Extracts task statistics from markdown content.
	 * @param {string} content
	 * @returns {TaskSummary}
	 */
	parseTasks(content) {
		if (!content || typeof content !== 'string') return { total: 0, completed: 0 }

		// 1. Try checkboxes first (Canonical)
		const totalCheckboxes = content.match(/^[ \t]*[-*+][ \t]+\[[ xX]\]/gm) || []
		if (totalCheckboxes.length > 0) {
			const completedCheckboxes = content.match(/^[ \t]*[-*+][ \t]+\[[xX]\]/gm) || []
			return {
				total: totalCheckboxes.length,
				completed: completedCheckboxes.length,
			}
		}

		// 2. Fallback to regular list items if no checkboxes found
		const listItems = content.match(/^[ \t]*[-*+][ \t]+(?!\s*\[)/gm) || []
		if (listItems.length > 0) {
			return {
				total: listItems.length,
				completed: 0, // We don't know if they are completed without checkboxes
			}
		}

		return { total: 0, completed: 0 }
	}

	/**
	 * @param {string} pkgPath
	 * @returns {Promise<import('@nan0web/inspect/src/domain/ArchitectureAuditor').Score|null>}
	 */
	async runArchAudit(pkgPath) {
		try {
			const auditor = new ArchitectureAuditor({ dir: `@app/${pkgPath}` }, { db: this._.db })
			const gen = auditor.run()
			let step = await gen.next()
			while (!step.done) {
				step = await gen.next()
			}
			if (step.value?.type === 'result') return step.value.data?.score
		} catch (e) {}
		return null
	}
}
