import { ModelAsApp, result, show, progress } from '@nan0web/ui'
import { ArchitectureAuditor } from '@nan0web/inspect'
import { Markdown } from '@nan0web/markdown'
import { createT } from '@nan0web/i18n'

/**
 * @typedef {Object} TaskSummary
 * @property {number} total
 * @property {number} completed
 */

/**
 * @typedef {Object} ModuleAuditResult
 * @property {string} name
 * @property {string} type
 * @property {string} path
 * @property {Record<string, TaskSummary>} files
 * @property {boolean} isCommercial
 * @property {string} license
 * @property {string} [goal]
 * @property {string} version
 * @property {any[]} [langs]
 * @property {any} [archScore]
 */

export default class AuditMonorepoApp extends ModelAsApp {
	static UI = {
		title: 'Ecosystem Audit 3.0',
		collecting: 'Collecting packages from pnpm-workspace.yaml',
		collected: 'Collected {count} packages',
		scanning: 'Analyzing {type}: {name}',
		completed: 'Audit completed. Found {count} active modules.',
		reportUpdated: 'Ecosystem report updated: STATUS.md',
		dbRequired: 'Database is required to run audit',
		colModule: 'Module',
		colVersion: 'Version',
		colGoal: 'Goal',
		colLangs: 'Langs',
		colTasks: 'Tasks',
		colHealth: 'Health',
		colLicense: 'License',
		generatedOn: 'Generated by AuditMonorepoApp 4.0 on {date}',
		healthUnknown: '🛠️ ?%',
		healthGood: '💎 {score}%',
		healthMedium: '🛠️ {score}%',
		healthBad: '⚠️ {score}%',
		core: '🚀 CORE ({version})',
		lab: '🏗️ LAB (In Dev)',
		seeds: '🌱 SEEDS (Ideas)',
		missingPurpose: '*Missing Purpose*',
	}

	/**
	 * @returns {AsyncGenerator<import('@nan0web/ui').Intent, import('@nan0web/ui').ResultIntent, any>}
	 */
	async *run() {
		if (this.help) return yield* super.run()

		const { t, db } = this._

		if (!db) {
			yield show(t(AuditMonorepoApp.UI.dbRequired))
			return result({ ok: false })
		}

		/** @type {ModuleAuditResult[]} */
		const scanned = []
		const standardDocs = [
			'{lang}/README.md',
			'{lang}/project.md',
			'README.md',
			'project.md',
			'next.md',
		]

		const pnpmWorkspace = await db.loadDocument('@app/pnpm-workspace.yaml')

		yield progress(t(AuditMonorepoApp.UI.collecting))

		const packages = []
		let i = 0

		for (const dir of pnpmWorkspace.packages) {
			const gen = db.browse('@app/' + dir.replace('/*', ''), {
				depth: 1,
				ignore: ['node_modules', '.git', 'dist', '.cache', 'chat'],
			})
			for await (const item of gen) {
				if ('package.json' === item.name) {
					yield progress(t(AuditMonorepoApp.UI.collecting), ++i)
					packages.push(item.parent)
				}
			}
		}
		yield show(t(AuditMonorepoApp.UI.collected, { count: packages.length }), 'success')

		i = 0
		for (const path of packages) {
			const [_, type, name = ''] = path.split('/')

			yield progress(t(AuditMonorepoApp.UI.scanning, { type, name }), ++i)

			// 1. Detect Identity & Version
			const pkgJson = await db.loadDocument(`${path}/package.json`)
			const version = pkgJson?.version ?? '0.0.0'

			// 2. Detect Locales via docs/index
			const docsIndex = await db.fetch(`${path}/docs/index`)
			const langs = docsIndex?.langs ?? []

			const docs = new Set()
			for (const pattern of standardDocs) {
				docs.add(pattern)
				for (const lang of langs) {
					const p = createT({}, 'en')
					docs.add(p(pattern, { lang: lang.locale }))
				}
			}
			const pages = Array.from(docs)
				.map(String)
				.filter((l) => !l.includes('{lang}'))
			// 3. Parse Tasks & Extract Goal
			/** @type {Record<string, TaskSummary>} */
			const files = {}
			let goal = null

			for (const target of pages) {
				const content = await db.loadDocument(`${path}/${target}`)
				if (content) {
					files[target] = this.parseTasks(content)
					if (!goal) goal = this.extractGoal(content)
				}
			}

			// 4. Run Architecture Audit via @nan0web/inspect
			const archScore = await this.runArchAudit(path)

			const item = {
				name,
				type,
				path,
				files,
				goal: goal || '',
				langs,
				version,
				license: pkgJson?.license || 'ISC',
				isCommercial: Boolean(pkgJson?.commercial),
				archScore,
			}

			scanned.push(item)
		}

		yield show(t(AuditMonorepoApp.UI.completed, { count: scanned.length }), 'success')

		// 6. Generate Report
		const mdContent = this.generateReport(scanned)
		await db.saveDocument('@app/STATUS.md', mdContent)

		yield show(t(AuditMonorepoApp.UI.reportUpdated), 'success')
		return result({ scanned })
	}

	/**
	 * @param {any} content
	 * @returns {string|null}
	 */
	extractGoal(content) {
		if (!content) return null
		let text = typeof content === 'string' ? content : String(content)
		if (!text) return null

		// Remove HTML comments completely
		text = text.replace(/<!--[\s\S]*?-->/g, '').trim()

		const lines = text
			.split('\n')
			.map((l) => l.trim())
			.filter(Boolean)

		// Find first non-title, non-list, non-image, non-link/navigation line
		for (const line of lines) {
			if (line.startsWith('#') || line.startsWith('-') || line.startsWith('*') || line.startsWith('+') || line.startsWith('!')) {
				continue
			}

			// Clean blockquotes or simple formatting
			let cleanLine = line.replace(/^>[ \t]*/, '').trim()

			// Skip navigation/translation/badge lines
			const lower = cleanLine.toLowerCase()
			if (
				lower.includes('english') ||
				lower.includes('українськ') ||
				lower.includes('читать') ||
				lower.includes('read in') ||
				lower.includes('status') ||
				lower.includes('build')
			) {
				if (cleanLine.includes('](')) continue
			}
			if (cleanLine.startsWith('[') && cleanLine.includes('](')) {
				continue
			}

			if (cleanLine) {
				return cleanLine.split('.')[0] + '.'
			}
		}

		return null
	}

	/**
	 * Find the highest version of packages in the monorepo
	 * @param {ModuleAuditResult[]} scanned
	 * @returns {string}
	 */
	getCoreVersion(scanned) {
		let maxVersion = '0.0.0'
		for (const item of scanned) {
			const v = item.version
			if (!v) continue
			const partsA = maxVersion.split('.').map(Number)
			const partsB = v.split('.').map(Number)
			let isGreater = false
			for (let i = 0; i < Math.max(partsA.length, partsB.length); i++) {
				const a = partsA[i] || 0
				const b = partsB[i] || 0
				if (b > a) {
					isGreater = true
					break
				} else if (b < a) {
					break
				}
			}
			if (isGreater) {
				maxVersion = v
			}
		}
		return maxVersion
	}

	/**
	 * Extracts task statistics from markdown content.
	 * @param {ModuleAuditResult[]} scanned
	 * @returns {string}
	 */
	generateReport(scanned) {
		const { t } = this._
		const doc = new Markdown()

		doc.write(t(AuditMonorepoApp.UI.title), 'h1')
		doc.write(t(AuditMonorepoApp.UI.generatedOn, { date: new Date().toISOString() }), 'blockquote')
		doc.write('')

		const version = this.getCoreVersion(scanned)
		const coreKey = t(AuditMonorepoApp.UI.core, { version })
		const labKey = t(AuditMonorepoApp.UI.lab)
		const seedsKey = t(AuditMonorepoApp.UI.seeds)

		// 1. Group by Maturity
		/** @type {Record<string, ModuleAuditResult[]>} */
		const categories = {
			[coreKey]: [],
			[labKey]: [],
			[seedsKey]: [],
		}

		const maxMajor = version.split('.')[0]

		for (const item of scanned) {
			const itemVersion = item.version || '0.0.0'
			const hasProject = !!item.files['project.md']
			const hasTasks =
				(item.files['next.md']?.total || 0) > 0 || (item.files['project.md']?.total || 0) > 0

			const itemMajor = itemVersion.split('.')[0]
			if (itemMajor === maxMajor && itemMajor !== '0') {
				categories[coreKey].push(item)
			} else if (hasProject || hasTasks) {
				categories[labKey].push(item)
			} else {
				categories[seedsKey].push(item)
			}
		}

		for (const [title, modules] of Object.entries(categories)) {
			if (modules.length === 0) continue

			doc.write(t(title), 'h2')
			const tableData = []

			for (const item of modules.sort((a, b) => a.name.localeCompare(b.name))) {
				const goal = item.goal || t(AuditMonorepoApp.UI.missingPurpose)

				let total = 0,
					completed = 0
				for (const f in item.files) {
					total += item.files[f].total || 0
					completed += item.files[f].completed || 0
				}

				// Health Score
				let health = '-'
				if (item.archScore !== undefined && item.archScore !== null) {
					const rawScore = typeof item.archScore === 'number'
						? item.archScore
						: typeof item.archScore.ratio === 'number'
							? Math.round(item.archScore.ratio * 100)
							: NaN
					const score = Math.round(rawScore)
					health = isNaN(score)
						? t(AuditMonorepoApp.UI.healthUnknown)
						: score >= 90
							? t(AuditMonorepoApp.UI.healthGood, { score })
							: score >= 60
								? t(AuditMonorepoApp.UI.healthMedium, { score })
								: t(AuditMonorepoApp.UI.healthBad, { score })
				}

				const versionLabel = item.version ? `\`v${item.version}\`` : '-'
				const tasksLabel = total > 0 ? `${completed}/${total}` : '-'
				const typeLabel = item.type === 'apps' ? '📱' : '📦'
				const langsLabel =
					item.langs && item.langs.length > 0
						? item.langs.map((l) => (typeof l === 'string' ? l : l.locale).toUpperCase()).join(', ')
						: '-'

				tableData.push({
					[t(AuditMonorepoApp.UI.colModule)]: `${typeLabel} **${item.name}**`,
					[t(AuditMonorepoApp.UI.colVersion)]: versionLabel,
					[t(AuditMonorepoApp.UI.colGoal)]: goal,
					[t(AuditMonorepoApp.UI.colLangs)]: langsLabel,
					[t(AuditMonorepoApp.UI.colTasks)]: tasksLabel,
					[t(AuditMonorepoApp.UI.colHealth)]: health,
					[t(AuditMonorepoApp.UI.colLicense)]: item.license,
				})
			}

			doc.table(tableData)
			doc.write('')
		}

		return doc.toString()
	}

	/**
	 * Extracts task statistics from markdown content.
	 * @param {string} content
	 * @returns {TaskSummary}
	 */
	parseTasks(content) {
		if (!content) return { total: 0, completed: 0 }
		const text = typeof content === 'string' ? content : String(content)
		if (!text) return { total: 0, completed: 0 }

		// 1. Try checkboxes first (Canonical)
		const totalCheckboxes = text.match(/^[ \t]*[-*+][ \t]+\[[ xX]\]/gm) || []
		if (totalCheckboxes.length > 0) {
			const completedCheckboxes = text.match(/^[ \t]*[-*+][ \t]+\[[xX]\]/gm) || []
			return {
				total: totalCheckboxes.length,
				completed: completedCheckboxes.length,
			}
		}

		// 2. Fallback to regular list items if no checkboxes found
		const listItems = text.match(/^[ \t]*[-*+][ \t]+(?!\s*\[)/gm) || []
		if (listItems.length > 0) {
			return {
				total: listItems.length,
				completed: 0, // We don't know if they are completed without checkboxes
			}
		}

		return { total: 0, completed: 0 }
	}

	/**
	 * @param {string} pkgPath
	 * @returns {Promise<any|null>}
	 */
	async runArchAudit(pkgPath) {
		try {
			const auditor = new ArchitectureAuditor({ dir: `@app/${pkgPath}` }, { db: this._.db })
			const gen = auditor.run()
			let step = await gen.next()
			while (!step.done) {
				step = await gen.next()
			}
			if (step.value?.type === 'result') return step.value.data?.score
		} catch (e) {}
		return null
	}
}
