import { ModelAsApp, result, show, progress } from '@nan0web/ui'
import { BuildWorkflowsApp } from '@nan0web/inspect'

export default class PrepareApp extends ModelAsApp {
	static help = {
		help: 'Prepare active workspace context, compile workflows, and synthesize prompt.md.',
		default: false,
	}

	static target = {
		help: 'Target package directory (e.g. packages/ui).',
		default: 'packages/ui',
		positional: true,
	}

	static step = {
		help: 'Target step number (1 to 9).',
		default: 3,
		type: 'number',
	}

	static UI = {
		title: '⚙️ NaN0Web Workspace Context Preparator',
		starting: 'Compiling workflows manifest...',
		compiled: 'Compiled workflows manifest.',
		sessionSaved: 'Saved session config to .agent/active_session.json (Step {step})',
		promptSaved: 'Prompt synthesized and saved to .gemini/prompt.md',
		errorNoDb: 'No database found',
	}

	/**
	 * @param {Partial<PrepareApp>} [data]
	 * @param {Partial<import('@nan0web/ui').ModelAsAppOptions>} [options]
	 */
	constructor(data = {}, options = {}) {
		super(data, options)
		/** @type {string} Target package directory (e.g. packages/ui). */
		this.target
		/** @type {number} Target step number (1 to 9). */
		this.step
	}

	/**
	 * @returns {AsyncGenerator<import('@nan0web/ui').Intent, import('@nan0web/ui').ResultIntent, any>}
	 */
	async *run() {
		if (this.help) return yield* super.run()

		const { t, db } = this._
		if (!db) {
			throw new Error(t(PrepareApp.UI.errorNoDb))
		}

		yield progress(t(PrepareApp.UI.starting))

		// 1. Compile workflows manifest using BuildWorkflowsApp execute helper
		const compileResult = await BuildWorkflowsApp.execute({ dir: db.location('@app') }, this._)
		yield show(
			t(PrepareApp.UI.compiled) + ` (${compileResult.ukCount} UK, ${compileResult.enCount} EN)`
		)

		// 2. Load global anchors
		const globalAnchorsPath = '@app/.agent/anchors.yaml'
		let globalAnchors = []
		const anchorsStat = await db.stat(globalAnchorsPath)
		if (anchorsStat && anchorsStat.exists) {
			const anchorsDoc = await db.loadDocument(globalAnchorsPath)
			globalAnchors = anchorsDoc?.global || []
		}

		// 3. Resolve active package configuration
		const activePkgPath = '@app/' + this.target
		const relativePkgDir = this.target
		const nan0ConfigPath = `${activePkgPath}/nan0web.nan0`

		const packageAnchors = []
		let packageName = ''
		const activeWorkflows = []

		const nan0Stat = await db.stat(nan0ConfigPath)
		if (nan0Stat && nan0Stat.exists) {
			const config = await db.loadDocument(nan0ConfigPath)
			packageName = config.name || ''

			for (const agent of config.agents || []) {
				for (const wfRelativePath of agent.workflows || []) {
					const fullWfPath = `${activePkgPath}/${wfRelativePath}`
					const wfStat = await db.stat(fullWfPath)
					if (wfStat && wfStat.exists) {
						const md = await db.loadDocument(fullWfPath)
						if (md.anchors) {
							for (const anchor of md.anchors) {
								packageAnchors.push(`${relativePkgDir}/${anchor}`)
							}
						}
						activeWorkflows.push({
							id: md.id || agent.id,
							name: md.name || agent.id,
							description: md.description || agent.description,
							file: `${relativePkgDir}/${wfRelativePath}`,
							anchors: (md.anchors || []).map((a) => `${relativePkgDir}/${a}`),
							inspectors: md.inspectors || agent.inspectors || [],
						})
					}
				}
			}
		}

		// 4. Merge anchors
		const allAnchors = [...new Set([...globalAnchors, ...packageAnchors])]

		// 5. Clean array-of-arrays based step mapping with zero code duplication
		const steps = [
			['jsdoc'], // Step 1
			['models'], // Step 2
			['welding'], // Step 3
			['adapters'], // Step 4
			['ui-cli'], // Step 5
			['ui-chat'], // Step 6
			['ui-web'], // Step 7
			['ui-mobile'], // Step 8
			['qa'], // Step 9
		]

		const targetStep = Math.max(1, Math.min(9, Number(this.step || 3)))
		const enabledInspectors = steps.slice(0, targetStep).flat()
		const allInspectors = steps.flat()
		const disabledInspectors = allInspectors.filter((x) => !enabledInspectors.includes(x))

		// 6. Write active session config
		const sessionData = {
			activePackage: packageName || relativePkgDir,
			currentStep: targetStep,
			enabledInspectors,
			disabledInspectors,
			anchors: allAnchors,
		}

		await db.saveDocument('@app/.agent/active_session.json', sessionData)
		yield show(t(PrepareApp.UI.sessionSaved, { step: targetStep }), 'success')

		// 7. Synthesize Prompt with clean Relative Paths instead of file:// absolute URLs
		const promptContent = `<!-- GENERATED BY NAN0WEB WORKFLOW COMPILER. DO NOT EDIT DIRECTLY. -->
# 🏗️ NaN0Web Agent Active Context & Prompt

## ⚓ Context Anchors (Кореневі Якорі Контексту)
Use the following files as strict references for domain models and coding standards. DO NOT drift into generic framework patterns:
${allAnchors.map((a) => `- ${a}`).join('\n')}

## 🔄 Active Workflows (Робочі Схеми для Поточного Завдання)
Apply the rules specified in these workflow guidelines during this task:
${activeWorkflows
	.map(
		(wf) => `
### 📑 Workflow: ${wf.name} (${wf.id})
- **File:** ${wf.file}
- **Description:** ${wf.description}
- **Anchors:** ${wf.anchors.length > 0 ? wf.anchors.join(', ') : 'None'}
- **Inspectors:** ${wf.inspectors.length > 0 ? wf.inspectors.join(', ') : 'None'}
`
	)
	.join('\n')}

## 🛡️ Step-Capped Verification (Каскадна Верифікація)
- **Active Phase:** Step ${targetStep}
- **Enabled Inspectors:** ${enabledInspectors.join(', ')}
- **Disabled Inspectors (Capped):** ${disabledInspectors.join(', ')}
*(Downstream validators are skipped for this step to maintain developer focus and fast iteration)*
`

		await db.saveDocument('@app/.gemini/prompt.md', promptContent)
		yield show(t(PrepareApp.UI.promptSaved), 'success')

		return result({
			ok: true,
			step: targetStep,
			activePackage: packageName || relativePkgDir,
		})
	}
}
