import { UiCommand } from "../../cli/Ui.js"
import { FileEntry } from "../../FileProtocol.js"
import { FileSystem } from "../../utils/FileSystem.js"
import { UiOutput } from "../../cli/UiOutput.js"

export default class Command extends UiCommand {
	static help = "Command description for user"
	static label = ""
	static example = "The example of the content of the command response ```bash\npnpm install\n```"
	/** @type {string} */
	cwd = ""
	/** @type {FileSystem} */
	fs = new FileSystem()
	/** @type {number} */
	timeout = 0
	/** @type {FileEntry} */
	file = new FileEntry()
	/** @type {import("../../FileProtocol.js").ParsedFile} */
	parsed = {}
	/**
	 * @param {Partial<Command>} input
	 */
	constructor(input = {}) {
		super()
		const {
			cwd = this.cwd,
			timeout = this.timeout,
			file = this.file,
			fs = this.fs,
			parsed = this.parsed,
		} = input
		this.cwd = String(cwd)
		this.timeout = Number(timeout)
		this.file = new FileEntry(file)
		this.fs = fs
		this.parsed = parsed
	}

	/**
	 * @returns {AsyncGenerator<boolean | string | UiOutput>}
	 *
	 *  - `boolean` - at the end to provide a result of the run
	 *  - `string` - the content for the next chat message. `#### [Generated by LLiMo](llimo)`
	 *  - `UiOutput` - show the result to user (output)
	 */
	async * run() {
		yield "Run method must be realized by subclasses"
	}
}
