import { UiCommand } from "../../cli/Ui.js"
import { FileEntry } from "../../FileProtocol.js"
import { FileSystem } from "../../utils/FileSystem.js"
import { UiOutput } from "../../cli/UiOutput.js"

export default class Command extends UiCommand {
	static description = "Command description for user"
	static label = ""
	static example = "The example of the content of the command response ```bash\npnpm install\n```"
	/** @type {string} */
	cwd
	/** @type {FileSystem} */
	fs
	/** @type {number} */
	timeout
	/** @type {FileEntry} */
	file
	/** @type {import("../../FileProtocol.js").ParsedFile} */
	parsed

	/**
	 * @param {Partial<Command> | Record<string, any>} [data={}]
	 * @param {Partial<import('@nan0web/ui').ModelAsAppOptions>} [options={}]
	 */
	constructor(data = {}, options = {}) {
		super(data, options)
		const opts = /** @type {any} */ (options)
		this.cwd = String(data.cwd || opts.cwd || "")
		this.timeout = Number(data.timeout || opts.timeout || 0)
		this.file = new FileEntry(data.file || opts.file || {})
		this.fs = data.fs || opts.fs || new FileSystem()
		this.parsed = data.parsed || opts.parsed || {}
	}

	/**
	 * @returns {AsyncGenerator<boolean | string | UiOutput>}
	 *
	 *  - `boolean` - at the end to provide a result of the run
	 *  - `string` - the content for the next chat message. `#### [Generated by LLiMo](llimo)`
	 *  - `UiOutput` - show the result to user (output)
	 */
	async * run() {
		yield "Run method must be realized by subclasses"
	}
}
