/**
 * @nan0web/icons — Build-time generator
 *
 * Reads react-icons source, extracts SVG data from GenIcon() calls,
 * and writes framework-agnostic icon modules to src/sets/*.js
 *
 * Usage: node scripts/generate.js [set1] [set2] ...
 * Example: node scripts/generate.js bs fa fi
 * (no args = generate all configured sets)
 */

import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SETS_DIR = join(__dirname, '..', 'src', 'sets')

/** Icon sets to generate (react-icons subpackage → output filename) */
const ICON_SETS = {
	bs: {
		module: 'react-icons/bs',
		description: 'Bootstrap Icons',
		author: 'Bootstrap Team',
		url: 'https://icons.getbootstrap.com/',
		license: 'MIT',
	},
	fa: {
		module: 'react-icons/fa',
		description: 'Font Awesome 5',
		author: 'Fonticons, Inc.',
		url: 'https://fontawesome.com/',
		license: 'CC BY 4.0',
	},
	fa6: {
		module: 'react-icons/fa6',
		description: 'Font Awesome 6',
		author: 'Fonticons, Inc.',
		url: 'https://fontawesome.com/',
		license: 'CC BY 4.0',
	},
	fi: {
		module: 'react-icons/fi',
		description: 'Feather Icons',
		author: 'Cole Bemis',
		url: 'https://feathericons.com/',
		license: 'MIT',
	},
	md: {
		module: 'react-icons/md',
		description: 'Material Design',
		author: 'Google',
		url: 'https://material.io/icons/',
		license: 'Apache 2.0',
	},
	hi: {
		module: 'react-icons/hi',
		description: 'Heroicons',
		author: 'Refactoring UI',
		url: 'https://heroicons.com/',
		license: 'MIT',
	},
	hi2: {
		module: 'react-icons/hi2',
		description: 'Heroicons 2',
		author: 'Refactoring UI',
		url: 'https://heroicons.com/',
		license: 'MIT',
	},
}

/**
 * Extract icon data JSON from a react-icons function.
 * react-icons functions look like:
 *   function IconName(props) { return GenIcon({...})(props) }
 *
 * @param {Function} iconFn
 * @returns {Object|null} Icon data { tag, attr, child }
 */
function extractIconData(iconFn) {
	const source = iconFn.toString()
	const match = source.match(/GenIcon\((\{[\s\S]*?\})\)\s*\(props\)/)
	if (!match) return null
	try {
		return new Function('return ' + match[1])()
	} catch {
		return null
	}
}

/**
 * Generate a single icon set module.
 *
 * @param {string} setName - e.g. 'bs'
 * @param {Object} config - { module, description }
 * @returns {Promise<{ count: number, size: number }>}
 */
async function generateSet(setName, config) {
	console.log(`  Generating ${setName} (${config.description})...`)

	const icons = await import(config.module)
	const entries = []
	let skipped = 0

	for (const [name, fn] of Object.entries(icons)) {
		if (typeof fn !== 'function') continue
		const data = extractIconData(fn)
		if (!data) {
			skipped++
			continue
		}
		data._name = name
		entries.push({ name, data })
	}

	// Generate module source
	const header = [
		'/**',
		` * ${config.description} — generated by @nan0web/icons`,
		` * Source: ${config.module}`,
		` * Icons: ${entries.length}`,
		` * Generated: ${new Date().toISOString().split('T')[0]}`,
		' * DO NOT EDIT — run: node scripts/generate.js',
		' */',
		'',
	].join('\n')

	const exports = entries
		.map((e) => `export const ${e.name} = ${JSON.stringify(e.data)}`)
		.join('\n')

	const content = header + exports + '\n'

	mkdirSync(SETS_DIR, { recursive: true })
	const outPath = join(SETS_DIR, `${setName}.js`)
	writeFileSync(outPath, content, 'utf-8')

	const sizeKB = (Buffer.byteLength(content) / 1024).toFixed(1)
	console.log(`  ✓ ${setName}: ${entries.length} icons → src/sets/${setName}.js (${sizeKB} KB)`)
	if (skipped) console.log(`    ⚠ ${skipped} skipped (no GenIcon data)`)

	return { count: entries.length, size: Buffer.byteLength(content) }
}

// --- Main ---
async function main() {
	const args = process.argv.slice(2)
	const setsToGenerate =
		args.length > 0
			? Object.fromEntries(args.map((s) => [s, ICON_SETS[s]]).filter(([, v]) => v))
			: ICON_SETS

	console.log(`@nan0web/icons generator`)
	console.log(`Sets: ${Object.keys(setsToGenerate).join(', ')}\n`)

	let totalIcons = 0
	let totalSize = 0

	for (const [name, config] of Object.entries(setsToGenerate)) {
		const result = await generateSet(name, config)
		totalIcons += result.count
		totalSize += result.size
	}

	// Generate catalog for playground
	const catalog = []
	for (const [name, config] of Object.entries(setsToGenerate)) {
		const icons = await import(config.module)
		for (const iconName of Object.keys(icons)) {
			if (typeof icons[iconName] !== 'function') continue

			// Generate tags by splitting camel case and lowercasing
			const terms = iconName
				.replace(/([A-Z])/g, ' $1')
				.toLowerCase()
				.trim()
				.split(' ')
			const tags = [...new Set(terms)].filter((t) => t.length > 1) // Remove 1-letter tags/prefixes usually

			catalog.push({
				id: iconName,
				set: name,
				tags: tags.join(' '),
			})
		}
	}

	const allSets = Object.fromEntries(
		Object.entries(ICON_SETS).map(([k, v]) => [
			k,
			{
				name: v.description,
				author: v.author,
				url: v.url,
				license: v.license,
			},
		]),
	)

	mkdirSync(join(__dirname, '..', 'play'), { recursive: true })
	writeFileSync(
		join(__dirname, '..', 'play', 'catalog.js'),
		`export const CACHE = ${JSON.stringify(catalog)};\n` +
			`export const SETS = ${JSON.stringify(allSets)};`,
	)
	console.log(`  ✓ Generated play/catalog.js with ${catalog.length} items`)

	console.log(`\n✓ Total: ${totalIcons} icons, ${(totalSize / 1024).toFixed(1)} KB`)
}

main().catch((e) => {
	console.error('Generator failed:', e)
	process.exit(1)
})
