/**
 * Utility helpers for tests.
 *
 * Provides a `clearDebugger` function to strip ANSI escape codes and
 * colour prefixes from test output.
 *
 * @module src/utils/test
 */

/**
 * Remove ANSI colour codes from a string.
 *
 * The test output may contain colour escape sequences generated by the
 * UI console (e.g., `\x1B[31m`). Stripping these makes string assertions
 * deterministic.
 *
 * @param {string} text - Raw output from the process.
 * @returns {string} Text without ANSI escape codes.
 */
export function clearDebugger(text) {
	if (typeof text !== 'string') return ''
	// Regex matches ANSI escape sequences.
	const ansiRegex = /\x1B\[[0-9;]*[mK]/g
	return text.replace(ansiRegex, '')
}
