export default mail;
import Address from './Address.js';
import Attachment from './Attachment.js';
import Email from './Email.js';
import MailDB from './MailDB.js';
import Message from './Message.js';
import Target from './Target.js';
import createMailer from './createMailer.js';
import mail from './mail.js';
export { Address, Attachment, Email, MailDB, Message, Target, createMailer, mail };
