#!/usr/bin/env node

import process from 'node:process'
import Logger from '@nan0web/log'
import { MemoryDB } from '@nan0web/test'
import I18nDb from '../src/I18nDb.js'
import { Language } from '../src/domain/Language.js'
import { CLiInputAdapter, Form } from '@nan0web/ui-cli'

let console = new Logger({ level: 'info' })

console.clear()
console.info(Logger.style(Logger.LOGO, { color: Logger.MAGENTA }))
console.info(Logger.style('=== @nan0web/i18n Interactive Playground ===\n', { color: Logger.MAGENTA }))

// Simulated translation dictionary logically generated by `npx i18n sync`
const db = new MemoryDB({
	predefined: new Map([
		[
			'data/uk/_/t.json',
			{
				'Language title': 'Назва мови',
				'Locale': 'Локаль',
				'Locale not found': 'Локаль не знайдено',
				'Invalid locale format': 'Невірний формат локалі',
				'Language icon': 'Іконка мови',
				'Select Language': '🌍 Оберіть мову:',
				'Choose demo form': '🔧 Виберіть дію:',
				'Language Form Demo': '📝 Демонстрація Форми',
				'Toggle Demo': '🔘 Демонстрація Перемикача',
				'Exit': '🚪 Вихід',
				'Yes': 'Так',
				'No': 'Ні',
				'Language settings': 'Налаштування мови',
				'You entered': 'Ви ввели',
			},
		],
		[
			'data/en/_/t.json',
			{
				'Language title': 'Language Name',
				'Locale': 'Locale Code',
				'Locale not found': 'Locale not found',
				'Invalid locale format': 'Invalid locale format',
				'Language icon': 'Language Icon',
				'Select Language': '🌍 Select Language:',
				'Choose demo form': '🔧 Choose action:',
				'Language Form Demo': '📝 Form Demo',
				'Toggle Demo': '🔘 Toggle Demo',
				'Exit': '🚪 Exit',
				'Yes': 'Yes',
				'No': 'No',
				'Language settings': 'Language settings',
				'You entered': 'You entered',
			},
		],
		[
			'data/uk/langs.json',
			[
				{ value: 'uk', label: 'Українська' },
				{ value: 'en', label: 'English' },
			],
		],
	]),
})

await db.connect()

const i18nDb = new I18nDb({
	db,
	locale: 'uk',
	tPath: '_/t.json',
	dataDir: 'data',
	srcDir: 'src',
	langs: await db.loadDocument('data/uk/langs.json'),
})

async function main() {
	const inputAdapter = new CLiInputAdapter({ console })

	process.on('SIGINT', () => {
		console.info('\nBye!')
		process.exit(0)
	})

	let currentLocale = 'uk'

	while (true) {
		// 1. Спочатку завжди питаємо мову
		const langs = i18nDb.getLangOptions()
		const langChoice = await inputAdapter.requestSelect({
			title: '🌍 Оберіть мову / Select Language:',
			options: langs.map((l) => ({
				label: l.value === currentLocale ? `[✔] ${l.label}` : `[ ] ${l.label}`,
				value: l.value,
			})),
		})

		if (langChoice.cancelled) break
		currentLocale = langChoice.value || 'uk'

		const t = await i18nDb.createT(currentLocale, '')
		inputAdapter.t = t

		// 2. Показуємо Форму
		console.info('\n--- ' + t('Language Form Demo') + ' ---')
		const handler = inputAdapter.createHandler(['quit', 'cancel', 'exit'])
		const selectHandler = inputAdapter.createSelectHandler()

		const form = new Form(new Language(), { inputFn: handler, selectFn: selectHandler, t })
		const res = await form.requireInput()
		if (!res.cancelled) {
			console.success(`\n✓ ${t('You entered')}:\n` + JSON.stringify(form.body, null, 2))
		}

		// 3. Показуємо Тогл (Налаштування)
		console.info('\n--- ' + t('Toggle Demo') + ' ---')
		const toggleRes = await inputAdapter.requestToggle({
			message: t('Language settings'),
			initial: true,
			active: t('Yes'),
			inactive: t('No'),
		})
		
		if (!toggleRes.cancelled) {
			console.success(`\n✓ ${t('You entered')}: ${toggleRes.value ? t('Yes') : t('No')}\n`)
		}

		// 4. Запитуємо чи хочемо повторити
		const nextAction = await inputAdapter.requestSelect({
			title: t('Choose demo form'),
			options: [
				{ label: '🔄 ' + t('Select Language') + ' (Restart)', value: 'restart' },
				{ label: '🚪 ' + t('Exit'), value: 'exit' },
			],
		})

		if (nextAction.cancelled || nextAction.value === 'exit') break
		
		console.clear()
		console.info(Logger.style('=== @nan0web/i18n Interactive Playground ===\n', { color: Logger.MAGENTA }))
	}

	console.success('\n=== End of Playground ===')
}

main().catch((err) => {
	console.error(err)
	process.exit(1)
})
